let cars = ["audi","bmw","maruti"];
cars.push("toyota");
console.log(cars);
cars.push("ford");
console.log(cars);
cars.pop();
console.log(cars);
cars.unshift("pagani");
console.log(cars);
cars.shift();
console.log(cars);